fix(remind): better args parsing

diff --git a/.local/bin/remind b/.local/bin/remind
--- a/.local/bin/remind
+++ b/.local/bin/remind
@@ -1,5 +1,6 @@
 #!/usr/bin/bash
 # Simple cli reminder. Add rm and list reminders.
+set -euo pipefail
 
 DATADIR="$HOME/.local/share/remind"
 DATAFILE="$DATADIR/reminders"
@@ -10,17 +11,32 @@ CAYN="\e[36m"
 RST="\e[0m"
 
 note() { echo -e "$@"; }
-die() { echo -e "$@"; exit 1; }
+die() { echo -e "remind: $@"; exit 1; }
 
-help() {
+usage() {
     cat <<EOF
-Track quick reminders. Add, delete and list.
-
 Commands
   add    add a new reminder to the list
   rm N   remove a reminder by index
   ls     list current active reminders
+
+Flags
+    -h,--help show help message
 EOF
+}
+
+help() {
+    cat <<EOF
+Track quick reminders.
+
+EOF
+    usage
+}
+
+die-usage() {
+    echo -e "remind: $@"
+    usage
+    exit 1
 }
 
 add-reminder() {
@@ -61,7 +77,7 @@ clear-all() {
 }
 
 main() {
-    case "$1" in
+    case "${1-}" in
         add)
             shift 1
             add-reminder "$@"
@@ -82,8 +98,11 @@ main() {
         -h|--help)
             help
             ;;
-        *)
+        "")
             list-reminders
+            ;;
+        *)
+            die-usage "invalid command '$1'"
             ;;
     esac
 }
